# Generated by Django 6.0.6 on 2026-07-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('action', '액션'), ('romance', '로맨스'), ('comedy', '코미디'), ('thriller', '스릴러'), ('sf', 'SF'), ('drama', '드라마')], default='action', max_length=100)),
                ('star', models.IntegerField()),
                ('time', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
